Repository OZ-Coding-School/oz_03_collabo-004-BE, pull requests merged in 2024-09, with the labels that each got.

#82 article_test_edit
  api/articles/tests/test_article_crud.py
Labels: Fix, Test

#96 프론트 로컬 테스트용 쿠키 세팅
  api/users/utils.py
Labels: Fix

#103 notification 수정
  api/notifications/serializers.py
  api/notifications/signals.py
Labels: Fix, Feature

#106 어드민 알림 추가
  api/notifications/migrations/0005_notification_is_admin_alter_notification_recipient_and_more.py
  api/notifications/models.py
  api/notifications/serializers.py
  api/notifications/signals.py
  api/notifications/urls.py
  api/notifications/views.py
Labels: enhancement

#120 어드민 api 수정
  api/reports/migrations/0003_commentreport_reported_article.py
  api/reports/models.py
  api/reports/views.py
  api/users/serializers.py
  api/users/views/user_crud_views.py
Labels: Feature
